# Generated by Django 5.2.3 on 2025-06-16 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logs1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("when", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "loggs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cabinets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=50)),
                ("name_teacher", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "cabinets",
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("when", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "loggs",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
            },
        ),
    ]
